ktor {
    deployment {
        port = 8098

        # Uncomment this to enable SSL. If this is enabled, a certificate must be provided (see
        # security section below)
        # sslPort = 8889
    }

    application {
        modules = [  world.respect.server.ApplicationKt.module ]
    }

    # School configuration
    school {
        directories {
            # By default the server will operate a single directory of all schools - if directories
            # virtualhost is set to true, then the server will only return directory entries where
            # SchoolDirectoryEntry.inDirectoryUrl matches the hostname (e.g. virtual host) used
            # to make the query.
            virtualhost = false
        }

        registration {
            # School self registration options:
            # disabled: not allowed
            # any-url: the user can enter any url in a textfield.
            # subdomain: the user is prompted to enter a subdomain of the subdomain-parent below
            mode = "any-url"

            # In subdomain registration mode, schools are registered as a subdomain of this parent
            # domain.
            subdomain-parent = "example.local"

            # If allowing registration of schools via a web form, then there MUST be a school
            # registration PIN
            # pin = "secret"

            # Uncomment to use a non-default port for school self-registration
            # subdomain-port = 8098
        }
    }

    # its only for the development, when the test fails in maestroi it will sent the database file to
    # the server if we make it true
    #e2etesting {
    #    enabled = true
    #}
}