ktor {
    deployment {
        port = 8098

        # Uncomment this to enable SSL. If this is enabled, a certificate must be provided (see
        # security section below)
        # sslPort = 8889
    }

    application {
        modules = [  world.respect.server.ApplicationKt.module ]
    }

    # School configuration
    school {
        registration {
            # School self registration options:
            # disabled: not allowed
            # any-url: the user can enter any url in a textfield.
            # subdomain: the user is prompted to enter a subdomain of the subdomain-parent below
            mode = "any-url"

            # In subdomain registration mode, schools are registered as a subdomain of this parent
            # domain.
            subdomain-parent = "example.local"

            # Uncomment to use a non-default port for school self-registration
            # subdomain-port = 8098
        }
    }
}