package world.respect.clitools.domain.testlaunchableapp

import io.ktor.http.Url
import world.respect.datalayer.school.opds.OpdsPublicationDataSource
import world.respect.lib.dataloadstate.DataLoadParams
import world.respect.lib.dataloadstate.ext.dataOrNull
import world.respect.lib.xapi.model.XapiStatementResult
import world.respect.lib.xapi.resources.XapiStatementsResource
import world.respect.shared.domain.launchapp.getlaunchoptionsforpublication.GetLaunchOptionsForPublicationUseCase
import kotlin.time.Instant

/**
 * Get the Xapi Statements that should have been generated by running a learning unit test.
 */
class GetXapiStatementsFromLearningUnitTestUseCase(
    private val opdsPublicationDataSource: OpdsPublicationDataSource,
    private val getLaunchOptionsForPublicationUseCase: GetLaunchOptionsForPublicationUseCase,
) {

    data class Result(
        val allStatements: XapiStatementResult,
        val activityId: String,
    )

    /**
     *
     * Works as follows:
     * a) Gets the ActivityID that would be used for the selected publication using
     *    GetLaunchOptionsForPublicationUseCase
     * b) Uses an XapiStatementResourceHttpClient to get all statements since the start time
     *    for the given activityId.
     */
    suspend operator fun invoke(
        publicationUrl: Url,
        testStartTime: Instant,
        statementResource: XapiStatementsResource,
    ): Result {
        val launchOptions = getLaunchOptionsForPublicationUseCase(
            publicationUrl = publicationUrl,
            publication = opdsPublicationDataSource.getByUrl(
                url = publicationUrl,
                params = DataLoadParams()
            ).dataOrNull() ?: throw IllegalStateException("Could not load $publicationUrl")
        )
        val activityId = launchOptions.options.first().activityId

        return Result(
            allStatements = statementResource.get(
                listParams = XapiStatementsResource.GetStatementParams(
                    since = testStartTime,
                )
            ).dataOrNull() ?: throw IllegalStateException("Could not load statements for publication url $publicationUrl"),
            activityId = activityId,
        )
    }

}