# Default list of directories as per ARCHITECTURE.md
# Add one line per directory invitecodeprefix=url
# e.g. 123=https://server.example.org/

# For local development - create a file in the same directory with the name local.properties that
# is gitignored. DO NOT CHANGE THIS FOR LOCAL DEVELOPMENT.
Algeria=https://dz.onrespect.app/
Angola=https://ao.onrespect.app/
Benin=https://bj.onrespect.app/
Botswana=https://bw.onrespect.app/
Burkina\ Faso=https://bf.onrespect.app/
Burundi=https://bi.onrespect.app/
Cabo\ Verde=https://cv.onrespect.app/
Cameroon=https://cm.onrespect.app/
Central\ African\ Republic=https://cf.onrespect.app/
Chad=https://td.onrespect.app/
Comoros=https://km.onrespect.app/
Congo=https://cg.onrespect.app/
Congo,\ Democratic\ Republic\ of\ the=https://cd.onrespect.app/
Côte\ dIvoire=https://ci.onrespect.app/
Djibouti=https://dj.onrespect.app/
Egypt=https://eg.onrespect.app/
Equatorial\ Guinea=https://gq.onrespect.app/
Eritrea=https://er.onrespect.app/
Eswatini=https://sz.onrespect.app/
Ethiopia=https://et.onrespect.app/
Gabon=https://ga.onrespect.app/
Gambia=https://gm.onrespect.app/
Ghana=https://gh.onrespect.app/
Guinea=https://gn.onrespect.app/
Guinea-Bissau=https://gw.onrespect.app/
Kenya=https://ke.onrespect.app/
Lesotho=https://ls.onrespect.app/
Liberia=https://lr.onrespect.app/
Libya=https://ly.onrespect.app/
Madagascar=https://mg.onrespect.app/
Malawi=https://mw.onrespect.app/
Mali=https://ml.onrespect.app/
Mauritania=https://mr.onrespect.app/
Mauritius=https://mu.onrespect.app/
Morocco=https://ma.onrespect.app/
Mozambique=https://mz.onrespect.app/
Namibia=https://na.onrespect.app/
Niger=https://ne.onrespect.app/
Nigeria=https://ng.onrespect.app/
Rwanda=https://rw.onrespect.app/
Sao\ Tome\ and\ Principe=https://st.onrespect.app/
Senegal=https://sn.onrespect.app/
Seychelles=https://sc.onrespect.app/
Sierra\ Leone=https://sl.onrespect.app/
Somalia=https://so.onrespect.app/
South\ Africa=https://za.onrespect.app/
South\ Sudan=https://ss.onrespect.app/
Sudan=https://sd.onrespect.app/
Tanzania,\ United\ Republic\ of=https://tz.onrespect.app/
Togo=https://tg.onrespect.app/
Tunisia=https://tn.onrespect.app/
Uganda=https://ug.onrespect.app/
Zambia=https://zm.onrespect.app/
Zimbabwe=https://zw.onrespect.app/
